# action.yml
name: "SFTP Deploy"
description: "Deploy using SFTP protocol"
inputs:
  username:
    description: "username"
    required: true
  password:
    description: "password"
    required: true
  server:
    description: "your sftp server"
    required: true
  port:
    description: "your sftp server port, default to 22"
    required: true
    default: "22"
  ssh_private_key:
    description: "private key from github secrets"
    required: true
  local_path:
    description: "local files that need to be transferred"
    required: true
    default: ./*
  remote_path:
    description: "destination on remote server"
    required: true
    default: /
  args:
    description: "sftp args"
    required: false
  deploy_webhook_url:
    description: "the url to trigger a new build/deployment"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.server }}
    - ${{ inputs.port }}
    - ${{ inputs.ssh_private_key }}
    - ${{ inputs.local_path }}
    - ${{ inputs.remote_path }}
    - ${{ inputs.args }}
    - ${{ inputs.deploy_webhook_url }}

branding:
  icon: "upload-cloud"
  color: "green"
